### ISSUE TITLE
Not working on provided example on README.md

### ISSUE THREAD

**Issue by albinscode** [Thiht/japscan-dl#1]
By running `./japscan-dl.sh 'One Punch Man' 1` we got for each page the message : 

~~~
Downloading page 1/18...curl: (22) The requested URL returned error: 404 
Failed to download page https://c.japscan.co/fb8mumumpsdbawdbfbsm22mbamfb8hmmcb2bcbmbpsmb0wumffub2hab8wdmbwpmcs8bqwfmam0mpwwbcbqmbdsbpf0mcw2mdbqm2bubqupbubsmu/sqbpabbmffm2s8b8sfbuwibhhfb2sfbbs2bcwhm8h0bbshmiyfbffdmahm2qfs2mwc2bspmcv2mu2imsaqmbbc203ub82cmadp2alqmdvbhhsdb8d/sbdy8hfvmwashw2bcw2bifidifisdwfl8wuyuhpydwaddff3sw23mhasfb83mhcv2wcsmwpymw0yuhfuuw2baw8vdwbfpfcd8fqyfhaf0wpvwwc3q/wb3sh.jpg from https://c.japscan.co/lel/One-Punch-Man/1/https://c.japscan.co/fb8mumumpsdbawdbfbsm22mbamfb8hmmcb2bcbmbpsmb0wumffub2hab8wdmbwpmcs8bqwfmam0mpwwbcbqmbdsbpf0mcw2mdbqm2bubqupbubsmu/sqbpabbmffm2s8b8sfbuwibhhfb2sfbbs2bcwhm8h0bbshmiyfbffdmahm2qfs2mwc2bspmcv2mu2imsaqmbbc203ub82cmadp2alqmdvbhhsdb8d/sbdy8hfvmwashw2bcw2bifidifisdwfl8wuyuhpydwaddff3sw23mhasfb83mhcv2wcsmwpymw0yuhfuuw2baw8vdwbfpfcd8fqyfhaf0wpvwwc3q/wb3sh.jpg
Maybe the previous file was a double page
Maybe the cookie is expired
~~~

This is probably due to a change from japscan. These urls are now fake ones only used as keys and some crypting stuffs are done to convert those urls.

On my side I started something with a pure puppeteer solution, I'll keep you in touch if I can go a step further.

**Comment by Thiht** [comment]
Yep, it doesn't work anymore, Japscan changed their way of doing and it's now pretty efficient and hard to bypass

I don't plan on updating myself since the changes are far from trivial

**Comment by Thiht** [comment]
Just looked into it and yep, they did a very good job :) 

I just added a deprecation notice in the readme. I will archive this repo and let it readonly for reference.
